apiVersion: v1
kind: Service
metadata:
  name: service-external-name
  namespace: basic-concepts
  labels:
    type: teste-service 
spec:
  type: ExternalName
  ExternalName: link-prototipo-demonstracao.com
  selector:
    type: teste-service
  ports:
    - port: 8080
      name: nginx
      targetPort: 8080
      nodePort: 30100
    - port: 443
      name: tomcat
      targetPort: 8443
      nodePort: 30101
