apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: first-daemonset 
  labels:
    app: monitoring

spec:
  template:
    metadata:
      name: my-container-daemonset
      labels:
        tier: frontend
        apps: monitoring
    spec:
      containers:
      - name: nginx-daemonset
        image: nginx:1.19.0

  selector:
    matchLabels:
      apps: monitoring