apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - prometheus/helmrepository.yaml
  - prometheus/helmrelease.yaml
  - grafana/helmrepository.yaml
  - grafana/helmrelease.yaml
