apiVersion: v1
kind: Secret
metadata:
  name: my-secret-env
  #namespace: basic-concepts
data: # Os valores devem estar em base-64
  user: YWRtaW4= 
  password: cGFzc3dvcmQ=
  
#immutable: true # Essa flag impede  o Secret de ser alterado depois de criado
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod-secret-env
  labels:
    name: secret-env
spec:
  containers:
  - name: my-container
    image: nginx
    envFrom: # COntainer referenciando de onde tirará as variaáveis de ambiente
      - secretRef:
          name: my-secret-env
          #optional: true # Container não espera o secret ser criado para subir