# apiVersion: v1
# kind: Secret
# metadata:
#   name: my-secret-vol
#   #namespace: basic-concepts
# data: # Os valores devem estar em base-64
#   user: YWRtaW4= 
#   password: cGFzc3dvcmQ=
  
# #immutable: true # Essa flag impede  o Secret de ser alterado depois de criado
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod-secret-vol
  labels:
    name: secret-vol
spec:
  containers:
  - name: my-container
    image: nginx
    envFrom: # COntainer referenciando de onde tirará as variaáveis de ambiente
      - secretRef:
          name: my-cm
          #optional: true # Container não espera o secret ser criado para subir  (spec.containers.envFrom.secretRef & spec.volumes.secret)
    volumeMounts:
      - name: secret-vol
        mountPath: /etc/secret-volume
        readOnly: true
  volumes:
  - name: secret-vol
    secret:
      secretName: my-secret-vol
      #optional: true # Container não espera o secret ser criado para subir  (spec.containers.envFrom.secretRef & spec.volumes.secret)
