apiVersion: v1
kind: Pod
metadata:
  name: my-pod-webserver
  namespace: basic-concepts
  labels:
    apps: my-app
    tier: front-end
spec:
  containers:
    - name: my-container-nginx
      image: nginx