apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: raizen
  title: Raízen
  description: Group representing Raízen.
  tags:
    - company
    - data
    - devops
spec:
  type: job
  children: []