apiVersion: v1
kind: Service
metadata:
  name: service-node-port
  namespace: basic-concepts
  labels:
    type: teste-service
spec:
  type: NodePort
  selector:
    type: teste-service
  ports:
    - port: 8080
      name: nginx
      targetPort: 8080
      nodePort: 30080
    - port: 443
      name: tomcat
      targetPort: 8443
      nodePort: 30443
