# Configuração de um Service para comunicação interna entre os pods do cluster (Cluster IP)
apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-service
  namespace: basic-concepts
spec:
  type: ClusterIP
  selector:
    type: web-server
  ports:
    - port: 80
      targetPort: 8080
    - port: 443
      targetPort: 8443