---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azure-spn #Nome visível do secret
  namespace: example-azure #namespace em que ele ficará
spec:
  encryptedData:
    ClientID: valor-criptografado
    ClientSecret: valor-criptografado # lembrar de, quando pegar o valor descriptografado, tira-lo da base64
  template:
    metadata: 
      creationTimestamp: null
      name: azure-spn
      namespace: example-azure
    type: Opaque

# Essa spn sera usada pelo CusterSecretStore para acessar os secrets dentro do key-vault criado
