apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: teste-external-secret-azure # nome do operator external secret
  namespace: external-secrets
spec:
  refreshInterval: 1h # tempo de atualização do secret
  secretStoreRef:
    kind: ClusterSecretStore  
    name: cluster-secret-store # NOme do local onde ele pegará as credenciais para acessar o key ault
  target:
    name: my-kubernetes-secrets # nome do secret visivel nos logs
  data:
  - secretKey: my-secret-key # nome do valor do valor do secret
    remoteRef:
      key: airflow-connections-teste # nome do caminho para o secret dentro do key-vault. Nele que estará o valor do secret
  - secretKey: my-secret-key-2 # nome do valor do valor do secret
    remoteRef:
      key: airflow-connections-teste-2 # nome do caminho para o secret dentro do key-vault. Nele que estará o valor do secret
