apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: backstage
type: Opaque
data:
  POSTGRES_HOST: CCCCC=  # postgres
  POSTGRES_PORT: ZXXX==  # 5432
  POSTGRES_USER: XXXXX
  POSTGRES_PASSWORD: XXXX==

