apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: backstage
type: Opaque
data:
  POSTGRES_HOST: cG9zdGdyZXM=  # postgres
  POSTGRES_PORT: NTQzMg==  # 5432
  POSTGRES_USER: YmFja3N0YWdl
  POSTGRES_PASSWORD: aHVudGVyMg==

