apiVersion: v1
kind: Service
metadata:
  name: service-load-balancer
  namespace: basic-concepts
  labels:
    type: teste-service
spec:
  type: LoadBalancer
  selector:
    type: teste-service
  ports:
    - port: 8080
      name: nginx
      targetPort: 8080
      nodePort: 30080
    - port: 443
      name: tomcat
      targetPort: 8443
      nodePort: 30443
