apiVersion: v1
kind: Pod
metadata:
  name: debian-pod
spec:
  containers:
  - name: debian-container
    image: debian
    command: ["sleep", "3600"]
    resources:
      limits:
        cpu: "1"
        memory: "512Mi"