apiVersion: v1
kind: Pod
metadata:
  name: web-server
  namespace: basic-concepts
  labels:
    type: web-app
spec:
  containers:
    - name: apache
      image: httpd
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"
    - name: tomcat
      image: tomcat
      ports:
        - containerPort: 8080
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"
