apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - monitoring/namespace.yaml
  - monitoring/prometheus/helmrepository.yaml
  - monitoring/prometheus/helmrelease.yaml
  - monitoring/grafana/helmrepository.yaml
  - monitoring/grafana/helmrelease.yaml
