apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: degree-bachelor-science-and-technology
  title: Degree
  description: Representation of a degree in Bachelor of Science and Technology.
  tags:
    - degree
    - computer-science
    - math
    - physics
spec:
  type: inventory
  owner: user:default/vinicius-juliasse-dantas
  dependencyOff:
    - group:default/unifesp
  links:
    - url: https://unifesp.br/campus/sjc/
      title: Site