apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: webscraping
  title: Web Scraping
  description: Web scraping system for data extraction
  tags:
    - data-extraction
    - automation
    - python
spec:
  owner: user:default/vinicius-juliasse-dantas
  