apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: skills-locations
  description: A collection of all the catalog entities
spec:
  type: file
  targets:
  - ./skills/skills/*.yaml
  - ./skills/type-skills/*.yaml

