apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: entities
  description: A collection of all the catalog entities
spec:
  type: file
  targets:
  # - ./apis/*.yaml
  - ./components/*.yaml
  - ./components/quests/*.yaml
  - ./domains/*.yaml
  - ./groups/*.yaml
  - ./resources/inventory/*.yaml
  - ./systems/skills/*.yaml
  - ./systems/quests/*.yaml
  # - ./templates/*.yaml
  - ./users/*.yaml
