apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: quests-locations
  description: A collection of all the catalog entities
spec:
  type: file
  targets:
  - ./quests/type-quests/*.yaml
  - ./quests/quests/projects/*.yaml
  - ./quests/quests/roles/*.yaml