apiVersion: v1
kind: Pod
metadata:
    name: emptydir-pod
    namespace: basic-concepts
spec:
    containers:
      - name: redis-pod
        image: redis
        volumeMounts: # Definição de montagem dos volume 
          - name: "cache-storage" # Sempre colocar entre aspas duplas 
            mountPath: "/cache" # Sempre colocar entre aspas duplas
        
    volumes:
      - name: cache-storage
        emptyDir: {} # Cria um emptyDir Vazio