apiVersion: batch/v1
kind: CronJob
metadata:
  name: first-cronjob # máximo de 52 caracteres
  #namespace: basic-concepts
spec: # Spec do CronJob
  startingDeadlineSeconds: 10 # Intervalo de tempo em que o cronjob Schedule conta a quantidade de trabalhos perdidos. Deve ser maior que 10 segundos
  failedJobsHistoryLimit: 5 # Quantidade de Jobs que falharam e que serão mantidos na memória
  successfulJobsHistoryLimit: 10 # Quantidade de Jobs que foram executados com sucesso e que serão mantidos na memória
  schedule: "* * * * *" # Schedule do CronJob. O padrão é o mesmo do cron do Linux. Esse padrão é o mesmo que a cada minuto
  jobTemplate:
    spec: # Spec do Job. Todas as especificações qque foram colocadas nos Jobs pode ser colocadas aqui
      completions: 10
      completionMode: "Indexed"
      parallelism: 3
      backoffLimit: 2
      template:
        spec: # Spec do Pod
          containers: 
          - name: cronjob-container
            image: busybox
            command:
              - /bin/sh
              - -c
              - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure


