apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cm
  #namespace: basic-concepts
data:
  database: mongodb
  database_uri: mongodb://mongodb:27017
  backgroung.color: red
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod-cm-vol
  labels:
    name: my-cm-vol
spec:
  containers:
  - name: my-container
    image: nginx
    envFrom:
    - configMapRef:
        name: my-cm # Referenciando o configmap
    volumeMounts: # Container referenciando o volume do configmap para poder acessar as variáveis de ambiente
    - name: my-volume 
      mountPath: /etc/config
      readOnly: true

  volumes:
  - name: my-volume
    ConfigMap: # Guardando as variáveis de ambiente dentro do Volume do POd
      name: my-cm